name: plugin-villagers
version: '1.0-1.21'
main: me.hiroshi.villagers_plugin.VillagersPlugin
api-version: '1.21'
commands:
  reputation:
    description: "This is a command"
    permission: villagers.set.discount
    usage: "/reputation [set] [radius] [height]"
    aliases: [vrep]
    permission-message: "&cYou don't have permissions to use this command!"